enum UpgradeID {
  UPGRADE_MODULE,
  MONEY_MACHINE,
  BUSINESS_MODULE,
  WORKER_MACHINES,
  LOWER_MANAGERS,
  MIDDLE_MANAGERS,
  FRIENDS_AND_FAM,
  MARKETING_MODULE,
  MARKETING_BUDGET,
}

export default UpgradeID